Complete overhaul of design repo
Joystream/design pull request #21
Opened 2019-12-17 22:36 UTC by blrhc

To be merged as part of branding rollout

2020-01-09 18:17 UTC, bwhm requested changes
I think the repo needs a little more structure. It's hard to navigate, and no one will even know we have a branding guide with rules etc. I'll list some thoughts below for you to consider:

1. I think we need to highlight the most important part of this repo - namely the brand guidelines. A header (like the landing repo, helpdesk, etc) with quick links to that, and potentially, other stuff you think people will come to the repo for, could be one way.
2. In the overview, provide some guidance and instructions for the user. Could be a table with links and explanations.
3. Improve the hierarchy of directories with and fewer more descriptive names. An easy example is to gather all the social media stuff in one dir, add a README.md, with a brief summary and maybe a ToC.
4. Make it very clear that archive is old and outdated branding, or perhaps better yet, delete it. It's still on the git blockchain anyway.
5. Not sure it's worth it, but a TL;DR of the branding guideline for use of main logo _might_ be of value.
6. Delete all jsg and staked assets from the repo.

2020-01-09 18:17 UTC, bwhm commented on README.md
>  Our primary audience for the next two years will be two categories of users we need to reach:
> ...be two categories of...

three?

2020-01-09 18:17 UTC, bwhm commented on archive/README.md
> +Our primary audience for the next two years will be two categories of users we need to reach:
> ...be two categories of...

three?

2020-01-14 23:15 UTC, blrhc commented
@bwhm Hopefully this is better now, though let me know if there are any tweaks that need to be made!

2020-01-15 11:04 UTC, bwhm requested changes
This is much better, but some minor tweaks would still be nice. 

Feel free to consider only implementing the most pertinent ones for now.

2020-01-15 11:04 UTC, bwhm commented on README.md
> +  - [Repository Index](#repository-index)
```suggestion
  - [Structure and Links](#structure-and-links)
```

I'm not sure if this is the best way of naming it, but `Repository Index` makes me think it's links to other repos...

2020-01-15 11:04 UTC, bwhm commented on README.md
> +# Table of Contents
```suggestion
Table of Contents
===
```
If you want to use the automatically generated ToC:
```
H1
==

H2
--
```
is equivalent to:
```
# H1

## H2
```
Where the former formatting is ignored in ToC.

2020-01-15 11:04 UTC, bwhm commented on README.md
> +|      `/blog`     | Assets for the [Joystream Blog](https://blog.joystream.org) |
Replace `/blog` with [/blog](/blog) or [blog](/blog) to make links. (For all of them really)

It would also be nice to have readme files and/or more descriptive names of the sub-directories, but that can be added later.

2020-01-15 11:04 UTC, bwhm commented on README.md
> +### Repository Index
```suggestion
## Structure and Links
```
Consider using H2 for this (and maybe other) subheaders.

2020-01-15 11:04 UTC, bwhm commented on README.md
> +|    `/favicon`    |           Favicon asset for the Joystream Website           |
`/favicon` is no longer a directory?

Consider gathering all website related assets under one directory.

2020-01-15 11:04 UTC, bwhm commented on README.md
> +|      `/blog`     | Assets for the [Joystream Blog](https://blog.joystream.org) |
Also, to allow for easier maintenance of this repo, it could be better to let all blog assets live in the communications repo. It's better to have it all here as well, but requires more work. Your call!

2020-01-15 13:42 UTC, blrhc commented on README.md
> +|      `/blog`     | Assets for the [Joystream Blog](https://blog.joystream.org) |
Yes, will make a PR for that too :)

2020-01-15 13:42 UTC, blrhc commented on README.md
> +|    `/favicon`    |           Favicon asset for the Joystream Website           |
Nice catch, will fix!

2020-01-15 13:46 UTC, blrhc commented on README.md
> +  - [Repository Index](#repository-index)
Yeah, very good point!

2020-01-18 22:59 UTC, blrhc commented
⬆️This most recently pushed one is the version without new individual READMEs for the directories (as these are not complete yet). I think the recommendation regarding putting the blog assets in the communications repo is a very good one so will also be making a PR for this shortly in that repo.

2020-01-19 14:42 UTC, bwhm commented
> ⬆️This most recently pushed one is the version without new individual READMEs for the directories (as these are not complete yet). I think the recommendation regarding putting the blog assets in the communications repo is a very good one so will also be making a PR for this shortly in that repo.

Please confirm if you want me to review now, or make these changes first!

2020-01-19 14:49 UTC, blrhc commented
> > ⬆️This most recently pushed one is the version without new individual READMEs for the directories (as these are not complete yet). I think the recommendation regarding putting the blog assets in the communications repo is a very good one so will also be making a PR for this shortly in that repo.
> 
> Please confirm if you want me to review now, or make these changes first!

I think review now and I will do a separate PR later :)

2020-01-20 15:49 UTC, bwhm approved these changes

2020-01-20 15:49 UTC, merged